#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by the ClassGenerator.ttinclude code generation file.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data;
using System.Linq;
using System.Linq.Expressions;
using System.Data.Common;
using System.Collections.Generic;
using Telerik.OpenAccess;
using Telerik.OpenAccess.Metadata;
using Telerik.OpenAccess.Data.Common;
using Telerik.OpenAccess.Metadata.Fluent;
using Telerik.OpenAccess.Metadata.Fluent.Advanced;
using SampleWebApplicationModel;

namespace SampleWebApplicationModel	
{
	public partial class User
	{
		private int _userID;
		public virtual int UserID
		{
			get
			{
				return this._userID;
			}
			set
			{
				this._userID = value;
			}
		}
		
		private string _username;
		public virtual string Username
		{
			get
			{
				return this._username;
			}
			set
			{
				this._username = value;
			}
		}
		
		private string _fullName;
		public virtual string FullName
		{
			get
			{
				return this._fullName;
			}
			set
			{
				this._fullName = value;
			}
		}
		
		private string _pass;
		public virtual string Pass
		{
			get
			{
				return this._pass;
			}
			set
			{
				this._pass = value;
			}
		}
		
		private DateTime? _lastLoginTime;
		public virtual DateTime? LastLoginTime
		{
			get
			{
				return this._lastLoginTime;
			}
			set
			{
				this._lastLoginTime = value;
			}
		}
		
		private int? _groupID;
		public virtual int? GroupID
		{
			get
			{
				return this._groupID;
			}
			set
			{
				this._groupID = value;
			}
		}
		
		private Group _group;
		public virtual Group Group
		{
			get
			{
				return this._group;
			}
			set
			{
				this._group = value;
			}
		}
		
	}
}
#pragma warning restore 1591
