// Code is generated by Telerik Add OpenAccess Service Wizard
// using WebApiRepositories.tt template

using System.Net;
using System.Net.Http;
using System.Web;
using System.Web.Http;
using Telerik.OpenAccess;
using SampleWebApplicationModel;

namespace SampleWebApplication
{
	public partial class AddressRepository : OpenAccessBaseRepository<SampleWebApplicationModel.Address, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

	public partial class DepartmentRepository : OpenAccessBaseRepository<SampleWebApplicationModel.Department, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

	public partial class EmployeeRepository : OpenAccessBaseRepository<SampleWebApplicationModel.Employee, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

	public partial class GroupRepository : OpenAccessBaseRepository<SampleWebApplicationModel.Group, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

	public partial class ProjectRepository : OpenAccessBaseRepository<SampleWebApplicationModel.Project, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

	public partial class TownRepository : OpenAccessBaseRepository<SampleWebApplicationModel.Town, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

	public partial class UserRepository : OpenAccessBaseRepository<SampleWebApplicationModel.User, SampleWebApplicationModel.EntitiesModel>
    {
	
    }

}
