//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebServicesUnitTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Marks
    {
        public int StudentId { get; set; }
        public string Subject { get; set; }
        public decimal Mark { get; set; }
    
        public virtual Students Students { get; set; }
    }
}
